### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by picciano** [ChatSecure/OTRKit#20]
Using bash build-all.sh on OS X 10.10.2
What am I doing wrong?

Making all in src
  CC     privkey.lo
  CC     context.lo
  CC     proto.lo
  CC     b64.lo
  CC     dh.lo
dh.c:43:18: warning: unused variable 'DH1536_MOD_LEN_BYTES' [-Wunused-const-variable]
static const int DH1536_MOD_LEN_BYTES = 192;
                 ^
1 warning generated.
  CC     mem.lo
  CC     message.lo
  CC     userstate.lo
  CC     tlv.lo
  CC     auth.lo
  CC     sm.lo
  CC     context_priv.lo
  CC     instag.lo
  CCLD   libotr.la
libtool: link: warning: library `/usr/local/lib/libgcrypt.la' was moved.
libtool: link: warning: library `/usr/local/lib/libgpg-error.la' was moved.
Making all in toolkit
  CC     otr_parse.o
  CC     readotr.o
  CC     parse.o
  CC     sha1hmac.o
  CCLD   otr_parse
libtool: link: warning: library `/usr/local/lib/libgcrypt.la' was moved.
libtool: link: warning: library `/usr/local/lib/libgpg-error.la' was moved.
ld: warning: directory not found for option '-L/Users/picciano1/Downloads/OTRKit-master/scripts/build/iPhoneSimulator-8.1-x86_64/lib'
ld: building for iOS Simulator, but linking against dylib built for MacOSX file '/usr/local/lib/libgpg-error.dylib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [otr_parse] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by picciano** [comment]
Disregard. For anyone else that runs into this, I had some old OS X-only builds of libgcrypt in /usr/local/lib that were interfering with this build. Once they were removed, build ran fine.

**Comment by chrisballinger** [comment]
Yeah I've seen that happen before as well. Should probably put a note
somewhere about that.
