### ISSUE TITLE
OTRKit Installation & Header not found

### ISSUE THREAD

**Issue by jevonch** [ChatSecure/OTRKit#30]
So, these are the steps that i've done :
1. Download as zip
2. Copy scripts and call $ bash build-all.sh
3. Nano podfile and pod install pod 'OTRKit', :git => 'https://github.com/ChatSecure/OTRKit.git'
4. Add this to podfile :
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
5. Everything's finished. But i can't import the OTRKit.h.What should i do/check?

**Comment by chrisballinger** [comment]
There is an issue with CocoaPods 1.0

**Comment by jevonch** [comment]
yep, i use cocoapods 1.0. So what's the solution?
